import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { SignInModal } from "@/components/auth/log-in/sign-in-modal";
import NavigationSidebar from "@/components/navigation/navigation-sidebar";
import { TanstackProvider } from "@/components/providers/tanstackprovider";
import { ThemeProvider } from "@/components/providers/themes-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-full">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TanstackProvider>
              <div className="h-full">
                <SignInModal />
                <div className="fixed inset-y-0 z-30 hidden h-full w-[72px] flex-col md:flex">
                  <NavigationSidebar />
                </div>
                <main className="h-full md:pl-[72px]">{children}</main>
              </div>
            </TanstackProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
